import json
import os
import requests
import textwrap
import time
import random

# Load from API .env explicitly
env_path = "/home/chris/aedra/api/.env"
GEMINI_API_KEY = "dummy-key"
GEMINI_MODEL = "gemini-2.0-flash"

if os.path.exists(env_path):
    with open(env_path, "r") as f:
        for line in f:
            if line.startswith("GEMINI_API_KEY="):
                GEMINI_API_KEY = line.split("=", 1)[1].strip().strip('"\'')
            if line.startswith("GEMINI_MODEL="):
                GEMINI_MODEL = line.split("=", 1)[1].strip().strip('"\'')

JUDGE_MODEL = "gemini-2.0-flash" # Use the latest stable flash model

def score_response(scenario, history):
    """
    Uses the LLM-as-judge to score the AI's response (or full history) against the predefined rubric.
    history can be a string (single response) or a list of dicts [{"user": "...", "ai": "..."}].
    """
    if not history:
        return {
            "Coherence": 0, "TaskCompletion": 0, "Accuracy": 0, "Persona": 0, "Resilience": 0,
            "OverallScore": 0.0,
            "Feedback": "No response generated by agent."
        }

    # Normalize history to a string for the prompt if it's a list
    if isinstance(history, list):
        formatted_history = ""
        for i, turn in enumerate(history):
            formatted_history += f"Turn {i+1}:\nUser: {turn.get('user')}\nAI: {turn.get('ai')}\n\n"
        last_ai_response = history[-1].get("ai", "") if history else ""
    else:
        formatted_history = f"User: {scenario.get('input', {}).get('message', '')}\nAI: {history}"
        last_ai_response = history

    rubric = scenario.get("rubric", {})
    ground_truth = scenario.get("ground_truth", "None provided.")
    
    prompt = f"""
You are an expert Property Management auditor grading an AI property management agent's performance.

SCENARIO CONTEXT:
Category: {scenario.get('category', 'Unknown')}
User Persona: {scenario.get('role', 'Unknown')}
Expected Intent: {scenario.get('expected', {}).get('intent', '')}
Expected Action: {scenario.get('expected', {}).get('action', '')}
Ground Truth Data: {ground_truth}

CONVERSATION HISTORY:
{formatted_history}

GRADING CRITERIA (Score 0 to 5):
1. Coherence: Did the agent maintain context throughout the conversation?
2. Task Completion: Did the agent actually resolve the user's issue or complete the requested task by the end? 
   (Note: If the task requires multiple turns and they were provided, did it finish? If only one turn was provided for a complex task, score based on progress.)
3. Accuracy: Did the agent correctly use names, dates, amounts, and adhere to the Ground Truth Data?
4. Persona: Did the agent stay in character (helpful, professional, compliant, natural language)?
5. Resilience: Did the agent handle any ambiguity, system constraints, or user frustration gracefully?

Output FORMAT MUST BE STRICT JSON:
{{
  "Coherence": <int 0-5>,
  "TaskCompletion": <int 0-5>,
  "Accuracy": <int 0-5>,
  "Persona": <int 0-5>,
  "Resilience": <int 0-5>,
  "OverallScore": <float 0-5>,
  "Feedback": "<short 1-2 sentence explanation focusing on what can be improved>"
}}
"""

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{JUDGE_MODEL}:generateContent?key={GEMINI_API_KEY}"
    
    data = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "response_mime_type": "application/json",
            "temperature": 0.0
        }
    }

    def _safe_json_loads(s: str):
        try:
            return json.loads(s)
        except Exception:
            # Sometimes the model wraps JSON in markdown fences or adds stray text.
            # Best-effort extraction of the first JSON object.
            start = s.find("{")
            end = s.rfind("}")
            if start != -1 and end != -1 and end > start:
                return json.loads(s[start : end + 1])
            raise

    try:
        max_retries = 10
        base_delay = 5.0
        for attempt in range(max_retries):
            response = requests.post(url, json=data, timeout=30)

            if response.status_code == 200:
                result = response.json()
                content = result["candidates"][0]["content"]["parts"][0]["text"]
                return _safe_json_loads(content)

            # Retry on transient failures / quota throttling.
            if response.status_code in (429, 500, 502, 503, 504):
                # Aggressive backoff for 429s
                wait = min(60.0, base_delay * (2**attempt)) + random.uniform(0, 5.0)
                print(
                    f"Grader API Error (Gemini): {response.status_code} - Quota exhausted? Retrying in {wait:.1f}s (Attempt {attempt+1}/{max_retries})"
                )
                time.sleep(wait)
                continue

            return {
                "Coherence": 0, "TaskCompletion": 0, "Accuracy": 0, "Persona": 0, "Resilience": 0,
                "OverallScore": 0.0,
                "Feedback": f"Grader failed (Gemini): HTTP {response.status_code}",
            }

        # Retries exhausted
        print(f"Grader API Error (Gemini): retries exhausted after HTTP {response.status_code}")
        return {
            "Coherence": 0, "TaskCompletion": 0, "Accuracy": 0, "Persona": 0, "Resilience": 0,
            "OverallScore": 0.0,
            "Feedback": "Grader failed (Gemini): retries exhausted",
        }
    except Exception as e:
        print(f"Exception during grading: {e}")
        return {
            "Coherence": 0, "TaskCompletion": 0, "Accuracy": 0, "Persona": 0, "Resilience": 0,
            "OverallScore": 0.0,
            "Feedback": f"Grader exception: {str(e)}"
        }

if __name__ == "__main__":
    # Test Grader
    test_scenario = {
        "role": "TENANT",
        "input": {"message": "Water hasn’t been working since morning"},
        "expected": {
            "intent": "report_maintenance",
            "action": "Acknowledge issue, gather unit details if missing, log maintenance request."
        },
        "rubric": {
            "Accuracy": "Correctly identified as a plumbing issue.",
            "Actionability": "Must offer to log a maintenance ticket.",
            "Tone": "Empathetic.",
            "Efficiency": "Directly asks for unit number if not known.",
            "Compliance": "No false promises."
        }
    }
    ai_resp = "I'm so sorry to hear the water is out! I've logged an urgent plumbing ticket. Could you please confirm your unit number so the vendor knows where to go?"
    
    print("Testing Grader...")
    res = score_response(test_scenario, ai_resp)
    print(json.dumps(res, indent=2))
