import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PortfolioReportData, CompanyRecord, getLogoUrl } from './backend-api';

// --- Shared Helpers ---

const loadImage = (url: string): Promise<HTMLImageElement | null> => {
    return new Promise((resolve) => {
        const img = new Image();
        const timeout = setTimeout(() => {
            console.error(`[PDF Gen] Logo load timeout for: ${url}`);
            resolve(null);
        }, 5000); // 5s timeout

        img.crossOrigin = "anonymous";
        img.onload = () => {
            clearTimeout(timeout);
            resolve(img);
        };
        img.onerror = (err) => {
            clearTimeout(timeout);
            console.error(`[PDF Gen] Logo load error for: ${url}`, err);
            resolve(null);
        };
        img.src = url;
    });
};

const resizeImage = (img: HTMLImageElement, maxDim: number = 800): string | HTMLImageElement => {
    const width = img.width;
    const height = img.height;

    if (width <= maxDim && height <= maxDim) return img;

    const canvas = document.createElement('canvas');
    let newWidth, newHeight;

    if (width > height) {
        newWidth = maxDim;
        newHeight = (height / width) * maxDim;
    } else {
        newHeight = maxDim;
        newWidth = (width / height) * maxDim;
    }

    canvas.width = newWidth;
    canvas.height = newHeight;
    const ctx = canvas.getContext('2d');
    if (!ctx) return img;

    ctx.drawImage(img, 0, 0, newWidth, newHeight);
    return canvas.toDataURL('image/jpeg', 0.85); 
};

async function drawBrandingHeader(
    doc: jsPDF,
    company: CompanyRecord | null,
    title: string,
    meta: { property: string; landlord: string; month: string },
    margin: number,
    rightAlignX: number
): Promise<number> {
    const logoUrl = getLogoUrl(company?.logo) || "/aedra-logo.png";
    const logo = await loadImage(logoUrl);
    if (logo) {
        const optimizedLogo = resizeImage(logo, 600);
        doc.addImage(optimizedLogo, 'JPEG', margin, margin, 25, 25, undefined, 'FAST');
    }

    const startY = 45; 
    doc.setFontSize(9);
    doc.setTextColor(40, 40, 40);
    doc.setFont("helvetica", "bold");
    doc.text(company?.name || "AEDRA MANAGEMENT", margin, startY);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    
    let currentInfoY = startY + 4;
    const address = company?.address || "P.O BOX 80000-80100, MOMBASA, KENYA";
    doc.text(address, margin, currentInfoY);
    currentInfoY += 4;

    const phone = company?.phone || "Property Management Office";
    doc.text(`TEL: ${phone}`, margin, currentInfoY);
    currentInfoY += 4;

    const email = company?.email || "support@aedra.co.ke";
    doc.text(`EMAIL: ${email}`, margin, currentInfoY);
    currentInfoY += 4;

    if (company?.pinNumber) {
        doc.setFont("helvetica", "bold");
        doc.text(`PIN: ${company.pinNumber}`, margin, currentInfoY);
        currentInfoY += 4;
    }

    const headerFinalY = Math.max(currentInfoY, startY + 20);

    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(title, rightAlignX, margin + 5, { align: 'right' });
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(`PROPERTY: ${meta.property.toUpperCase()}`, rightAlignX, margin + 12, { align: 'right' });
    doc.text(`LANDLORD: ${meta.landlord.toUpperCase()}`, rightAlignX, margin + 17, { align: 'right' });
    doc.text(`MONTH: ${meta.month.toUpperCase()}`, rightAlignX, margin + 22, { align: 'right' });

    return headerFinalY;
}

function drawFooter(doc: jsPDF) {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
            `Page ${i} of ${pageCount} | Generated by Aedra AI Management System`,
            doc.internal.pageSize.width / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }
}

// --- Exported Functions ---

/**
 * ORIGINAL Remittance Report - DO NOT MODIFY OUTPUT PATTERN
 */
export async function generateFinancialStatementPdf(
    data: PortfolioReportData, 
    landlordName: string, 
    company: CompanyRecord | null,
    propertyUnits?: any[]
) {
    const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
        compress: true
    }); 
    const property = data.property;
    const margin = 14;
    const pageWidth = doc.internal.pageSize.width;
    const rightAlignX = pageWidth - margin;

    const headerFinalY = await drawBrandingHeader(
        doc, 
        company, 
        "REMITTANCE REPORT", 
        { 
            property: property.name, 
            landlord: landlordName, 
            month: data.month 
        }, 
        margin, 
        rightAlignX
    );

    const tableRows: any[] = [];
    const vatRate = 0.16;
    const commissionPct = property.commissionPercentage || 0;

    let sumInvoice = 0;
    let sumCollection = 0;
    let sumOutstanding = 0;
    let sumRemitted = 0;
    let sumFeeVat = 0;
    let sumPayable = 0;

    data.tenantPayments.forEach(tp => {
        const invoiceAmt = tp.rentAmount || 0;
        const currentCollection = tp.paidThisMonth || 0;
        const outstanding = tp.totalBalance || 0;
        
        const managementFee = (currentCollection * commissionPct) / 100;
        const vat = managementFee * vatRate;
        const totalDeduction = managementFee + vat;
        
        const amountRemitted = currentCollection; 
        const amountPayable = currentCollection - totalDeduction;

        sumInvoice += invoiceAmt;
        sumCollection += currentCollection;
        sumOutstanding += outstanding;
        sumRemitted += amountRemitted;
        sumFeeVat += totalDeduction;
        sumPayable += amountPayable;

        tableRows.push([
            tp.unit,
            tp.name,
            invoiceAmt.toLocaleString(),
            currentCollection.toLocaleString(),
            outstanding.toLocaleString(),
            amountRemitted.toLocaleString(),
            totalDeduction.toLocaleString(),
            amountPayable.toLocaleString()
        ]);
    });

    if (propertyUnits) {
        const occupiedUnitNumbers = new Set(data.tenantPayments.map(tp => tp.unit));
        propertyUnits.forEach(u => {
            if (!occupiedUnitNumbers.has(u.unitNumber)) {
                tableRows.push([u.unitNumber, "VACANT", "", "", "", "", "", ""]);
            }
        });
    }

    autoTable(doc, {
        startY: headerFinalY + 5,
        head: [['UNIT', 'TENANT', 'INVOICE AMT', 'COLLECTION', 'BALANCE', 'REMITTED', 'FEE + VAT', 'PAYABLE']],
        body: tableRows,
        foot: [[
            'TOTALS',
            '',
            sumInvoice.toLocaleString(),
            sumCollection.toLocaleString(),
            sumOutstanding.toLocaleString(),
            sumRemitted.toLocaleString(),
            sumFeeVat.toLocaleString(),
            sumPayable.toLocaleString()
        ]],
        theme: 'striped',
        headStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold', lineWidth: 0.1, lineColor: [200, 200, 200] },
        footStyles: { fillColor: [245, 245, 245], textColor: [0, 0, 0], fontStyle: 'bold', lineWidth: 0.1, lineColor: [200, 200, 200] },
        styles: { fontSize: 7, cellPadding: 2, font: 'helvetica', lineWidth: 0.1, lineColor: [230, 230, 230] },
        columnStyles: {
            0: { cellWidth: 15 },
            1: { cellWidth: 45 },
            2: { halign: 'right' },
            3: { halign: 'right' },
            4: { halign: 'right' },
            5: { halign: 'right' },
            6: { halign: 'right' },
            7: { halign: 'right', fontStyle: 'bold' }
        }
    });

    drawFooter(doc);
    const filename = `${property.name.replace(/\s+/g, '_')}_Remittance_Report_${data.month.replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);
}

/**
 * NEW Property Financial Ledger - Replaces CSV
 */
export async function generatePropertyFinancialLedgerPdf(
    data: PortfolioReportData, 
    landlordName: string, 
    company: CompanyRecord | null,
    propertyUnits?: any[]
) {
    const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4',
        compress: true
    }); 
    const property = data.property;
    const margin = 14;
    const pageWidth = doc.internal.pageSize.width;
    const rightAlignX = pageWidth - margin;

    const headerFinalY = await drawBrandingHeader(
        doc, 
        company, 
        "PROPERTY FINANCIAL LEDGER", 
        { 
            property: property.name, 
            landlord: landlordName, 
            month: data.month 
        }, 
        margin, 
        rightAlignX
    );

    // --- 1. Unit Breakdown Table ---
    const tableRows: any[] = [];
    let sumExpected = 0;
    let sumActual = 0;
    let sumBalance = 0;

    data.tenantPayments.forEach(tp => {
        const expected = tp.rentAmount || 0;
        const actual = tp.paidThisMonth || 0;
        const balance = expected - actual;

        sumExpected += expected;
        sumActual += actual;
        sumBalance += balance;

        tableRows.push([
            tp.unit,
            tp.name,
            expected.toLocaleString(),
            actual.toLocaleString(),
            balance.toLocaleString()
        ]);
    });

    if (propertyUnits) {
        const occupiedUnitNumbers = new Set(data.tenantPayments.map(tp => tp.unit));
        propertyUnits.forEach(u => {
            if (!occupiedUnitNumbers.has(u.unitNumber)) {
                tableRows.push([u.unitNumber, "VACANT", "", "", ""]);
            }
        });
    }

    autoTable(doc, {
        startY: headerFinalY + 5,
        head: [['UNIT', 'TENANT', 'EXPECTED RENT', 'ACTUAL PAID', 'BALANCE']],
        body: tableRows,
        foot: [[
            'TOTALS',
            '',
            sumExpected.toLocaleString(),
            sumActual.toLocaleString(),
            sumBalance.toLocaleString()
        ]],
        theme: 'striped',
        headStyles: { fillColor: [255, 255, 255], textColor: [0, 0, 0], fontStyle: 'bold', lineWidth: 0.1, lineColor: [200, 200, 200] },
        footStyles: { fillColor: [245, 245, 245], textColor: [0, 0, 0], fontStyle: 'bold', lineWidth: 0.1, lineColor: [200, 200, 200] },
        styles: { fontSize: 8, cellPadding: 3, font: 'helvetica' },
        columnStyles: {
            0: { cellWidth: 20 },
            1: { cellWidth: 60 },
            2: { halign: 'right' },
            3: { halign: 'right' },
            4: { halign: 'right', fontStyle: 'bold' }
        }
    });

    // --- 2. Building Summary Table ---
    const finalY = (doc as any).lastAutoTable.finalY + 10;
    
    const totals = data.totals || {};
    const commissionPct = property.commissionPercentage || 0;
    const commissionAmount = ((totals.payments || 0) * commissionPct) / 100;
    
    const expensesByCategory = totals.expensesByCategory || [];
    const maintenanceExpenses = expensesByCategory
        .filter(e => ['MAINTENANCE', 'REPAIR'].includes(e.category))
        .reduce((sum, e) => sum + e.amount, 0);
    const utilityExpenses = expensesByCategory
        .filter(e => e.category === 'UTILITY')
        .reduce((sum, e) => sum + e.amount, 0);
    const otherExpenses = (totals.expenses || 0) - maintenanceExpenses - utilityExpenses;
    const netLandlordShare = (totals.payments || 0) - commissionAmount - (totals.expenses || 0);

    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text("BUILDING SUMMARY (FOR THE MONTH)", margin, finalY);

    autoTable(doc, {
        startY: finalY + 2,
        margin: { left: margin },
        tableWidth: 100,
        body: [
            ["TOTAL RENT COLLECTED", `KES ${(totals.payments || 0).toLocaleString()}`],
            ["AGENT COMMISSION", `KES ${commissionAmount.toLocaleString()} (${commissionPct}%)`],
            ["MAINTENANCE & REPAIRS", `KES ${maintenanceExpenses.toLocaleString()}`],
            ["UTILITIES", `KES ${utilityExpenses.toLocaleString()}`],
            ["OTHER EXPENSES", `KES ${otherExpenses.toLocaleString()}`],
            ["NET LANDLORD SHARE", `KES ${netLandlordShare.toLocaleString()}`]
        ],
        theme: 'plain',
        styles: { fontSize: 9, cellPadding: 2 },
        columnStyles: {
            0: { cellWidth: 60, fontStyle: 'bold' },
            1: { halign: 'right' }
        },
        didParseCell: (data) => {
            if (data.row.index === 5) { // Net Landlord Share
                data.cell.styles.fontStyle = 'bold';
                data.cell.styles.fillColor = [240, 255, 240]; // Light green
                data.cell.styles.textColor = [0, 100, 0];
            }
        }
    });

    drawFooter(doc);
    const filename = `${property.name.replace(/\s+/g, '_')}_Financial_Ledger_${data.month.replace(/\s+/g, '_')}.pdf`;
    doc.save(filename);
}
